### PR TITLE
Resolve "Add proper position uncertainties"

### PR DESCRIPTION
**Pull request by mattpitkin**
In response to #59 this PR converts the errors on RAJ and DECJ into position errors on RAJD and DECJD, e.g.:

```
>>> from psrqpy import QueryATNF
>>> q = QueryATNF(params=["PSRJ", "RAJ", "DECJ", "RAJD", "DECJD"])
>>> q.table[:10]["PSRJ", "RAJD", "RAJD_ERR"]  # show first ten entries
<Table length=10>
    PSRJ           RAJD               RAJD_ERR       
                   deg                  deg          
   str12         float64              float64        
----------- ------------------ ----------------------
 J0002+6216           0.742375  8.333333333333333e-05
 J0006+1834               1.52  0.0008333333333333333
 J0007+7303  1.757083333333333  0.0008333333333333333
   J0011+08  2.891666666666666                  0.475
 J0014+4746 3.5739583333333327 0.00016666666666666666
 J0023+0923  5.820321575672663                     --
J0024-7204C  5.959810833333333 4.1666666666666667e-07
J0024-7204D  6.057837166666666                2.5e-07
J0024-7204E  6.046271999999999 2.0833333333333333e-07
J0024-7204F  6.016064458333333 4.1666666666666667e-07
```
The RAJD_ERR has units of degrees, so can be converted to, e.g., radians with:

```
>>> q.table[:10]["RAJD_ERR"].to("rad")
<Quantity [1.45444104e-06, 1.45444104e-05, 1.45444104e-05, 8.29031395e-03,
           2.90888209e-06,            nan, 7.27220522e-09, 4.36332313e-09,
           3.63610261e-09, 7.27220522e-09] rad>
```
Or, you could get it for an individual pulsar with, e.g.,

```
>>> print(q.get_pulsar("J0534+2200")["RAJD_ERR"])
       RAJD_ERR       
         deg          
----------------------
2.0833333333333333e-05
```

### CODE REVIEW

**Comment by dlakaplan** [comment]
This looks good, although I'd need to use it to be sure.  Thanks.

Could you check that it works for J0034+69, where the RA position is just given as:
```
#     NAME                     RAJ
…
36    J0034-0534  bhl+94     00:34:21.83422   8.0e-05   dcl+16
37    B0031-07  lvw69a     00:34:08.8703    1.0e-04   cbv+09
38    J0034+69  slr+14     00:34            3.0e+00   slr+14
```
so the uncertainty should be 3 minutes (not seconds)?

**Comment by mattpitkin** [comment]
For J0034+69 I get:

```
>>> print(q.get_pulsar("J0034+69")["RAJD_ERR"])                                                                                                                                 
RAJD_ERR
  deg   
--------
    0.75
```

which looks correct.

**Comment by mattpitkin** [comment]
@dlakaplan If you're happy, I'll merge this and upload a new version to PyPI.

**Comment by dlakaplan** [comment]
Sounds good.  I could do some separate tests on the branch if you want, but it looks good.  I'd say merge away.

**Comment by mattpitkin** [comment]
I've merged this and pushed a new release. Let me know if you do encounter any bugs and I can easily make another release.

**Pull request merged**
